#이승우
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/melocal?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234

##성재님
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/recur?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1207

#전성영
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234

  # h2 database
  #    url: jdbc:h2:mem:testdb
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ono
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #        use_sql_comments: true

  logging:
    level:
      org.hibernate.SQL: debug
  #      org.hibernate.type: trace

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8090

#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11:
#            debug

jwt:
  secret:
    key: 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk

